#!/usr/bin/env bash
# ============================================================================
# utilities/list-vaulted-vars.sh
# ============================================================================
# Scans inventory/group_vars/ (and, with --exports, exports/) for every
# {{ vaulted_* }} placeholder referenced by curated/exported objects, and prints
# a secrets.yml SKELETON to stdout — one "vaulted_x: CHANGEME" per variable.
#
# It writes nothing to disk (so no secret ever lands in a tracked file by
# accident). Redirect it yourself, fill in the values, then encrypt:
#
#   bash utilities/list-vaulted-vars.sh > inventory/group_vars/dev/secrets.yml
#   # edit the file, replace each CHANGEME with the real value
#   ansible-vault encrypt inventory/group_vars/dev/secrets.yml --vault-id dev@prompt
#
# Usage:
#   utilities/list-vaulted-vars.sh              # scan inventory/group_vars only
#   utilities/list-vaulted-vars.sh --exports    # also scan exports/
# ============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
scan_dirs=("$ROOT/inventory/group_vars")
[[ "${1:-}" == "--exports" ]] && scan_dirs+=("$ROOT/exports")

vars="$(grep -rhoE 'vaulted_[A-Za-z0-9_]+' "${scan_dirs[@]}" 2>/dev/null | sort -u || true)"

echo "---"
echo "# secrets.yml skeleton generated by utilities/list-vaulted-vars.sh"
echo "# Replace every CHANGEME with the real value, then ansible-vault encrypt."
if [[ -z "$vars" ]]; then
  echo "# (no vaulted_* placeholders found yet — curate some objects first)"
else
  while IFS= read -r v; do
    echo "${v}: CHANGEME"
  done <<< "$vars"
fi
