#!/usr/bin/env bash
# ============================================================================
# .devcontainer/post-create.sh
# ============================================================================
# Runs once, inside the container, after it is created. It:
#   1. Writes ~/.ansible.cfg IN THE CONTAINER (never committed) with the
#      Automation Hub galaxy server so certified collections can install.
#   2. Installs the pinned collections from collections/requirements.yml.
#   3. Installs the Copilot CLI (best effort).
#   4. Installs a git pre-commit hook that runs the secret-hygiene guards.
#
# This intentionally does NOT create a project-local ansible.cfg — that would
# shadow a real ~/.ansible.cfg. The file written here lives in the container's
# home and is thrown away with the container.
# ============================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ANSIBLE_CFG="${HOME}/.ansible.cfg"

# Automation Hub URLs. Two endpoints are required, not one:
#   certified (content/published/) ships ansible.platform + ansible.controller
#   validated (content/validated/) ships infra.aap_configuration*
# A single endpoint cannot satisfy collections/requirements.yml, and the
# community Galaxy fallback does not carry the certified collections at all.
#
# Override either one for a customer's private hub by exporting it before
# "Reopen in Container" (see runbook 00). AH_URL is still honoured as an alias
# for the validated endpoint, which is what earlier docs described.
AH_CERTIFIED_URL="${AH_CERTIFIED_URL:-https://console.redhat.com/api/automation-hub/content/published/}"
AH_VALIDATED_URL="${AH_VALIDATED_URL:-${AH_URL:-https://console.redhat.com/api/automation-hub/content/validated/}}"
AH_AUTH_URL="https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"

echo "==> aap_config dev container setup"

# --- 1. Automation Hub token -------------------------------------------------
# Prefer a token passed from the host env (remoteEnv AH_TOKEN); otherwise prompt.
if [[ -z "${AH_TOKEN:-}" ]]; then
  echo
  echo "An Automation Hub API token is needed to install Red Hat certified"
  echo "collections. Get one at: https://console.redhat.com  ->  Automation Hub"
  echo "-> API token. (Leave blank to skip; you can re-run this script later.)"
  read -r -s -p "Automation Hub token: " AH_TOKEN
  echo
fi

if [[ -n "${AH_TOKEN:-}" ]]; then
  cat > "${ANSIBLE_CFG}" <<EOF
# Generated by .devcontainer/post-create.sh inside the container. Not committed.
[galaxy]
server_list = rh_certified, rh_validated, community

[galaxy_server.rh_certified]
url = ${AH_CERTIFIED_URL}
auth_url = ${AH_AUTH_URL}
token = ${AH_TOKEN}

[galaxy_server.rh_validated]
url = ${AH_VALIDATED_URL}
auth_url = ${AH_AUTH_URL}
token = ${AH_TOKEN}

[galaxy_server.community]
url = https://galaxy.ansible.com/
EOF
  chmod 600 "${ANSIBLE_CFG}"
  echo "==> wrote ${ANSIBLE_CFG} (mode 600, container-local)"
else
  echo "!! No token provided — skipping ~/.ansible.cfg. Certified collections"
  echo "   will not install until you re-run: bash .devcontainer/post-create.sh"
fi

# --- 2. Collections ----------------------------------------------------------
if [[ -f "${ANSIBLE_CFG}" ]]; then
  echo "==> installing collections from collections/requirements.yml"
  ansible-galaxy collection install -r "${REPO_ROOT}/collections/requirements.yml"
fi

# --- 3. Copilot CLI (best effort) --------------------------------------------
echo "==> installing GitHub Copilot CLI"
if npm install -g @github/copilot >/dev/null 2>&1; then
  echo "==> Copilot CLI installed. Run 'copilot' once to log in (device flow)."
else
  echo "!! Copilot CLI install failed. Fallbacks: 'gh extension install github/gh-copilot'"
  echo "   or use Copilot Chat in VS Code. Runbook prompts work in any AI tool."
fi

# --- 4. Pre-commit secret-hygiene hook --------------------------------------
HOOK="${REPO_ROOT}/.git/hooks/pre-commit"
if [[ -d "${REPO_ROOT}/.git" ]]; then
  cat > "${HOOK}" <<'EOF'
#!/usr/bin/env bash
# Auto-installed by .devcontainer/post-create.sh. Blocks secret mistakes before
# they enter local git history. CI runs the same guards as a backstop.
set -e
ROOT="$(git rev-parse --show-toplevel)"
bash "${ROOT}/utilities/check-vault-encrypted.sh"
bash "${ROOT}/utilities/scan-exports.sh"
EOF
  chmod +x "${HOOK}"
  echo "==> installed .git/hooks/pre-commit (vault + export secret guards)"
fi

echo
echo "==> Done. Next step: open docs/runbooks/01-devcontainer.md"
